version: '3.8'

services:
  web:
    image: mattrayner/lamp:latest
    container_name: hemnet_commuter
    ports:
      - "8004:80"
    volumes:
      - ./app:/app
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=hemnet_commuter

volumes:
  mysql:
  app: